### ISSUE TITLE
Not all updates require reboot

### ISSUE THREAD

**Issue by ChristopherA** [thisaaronm/macOS_softwareUpdate#2]
Not all updates require a reboot, but I believe this script reboots it for all updates.

I came to this repo seeking solutions why my prepare-osx.sh script in https://github.com/ChristopherA/prepare-osx-for-webdev wasn't working as smoothly anymore. In many ways your script demonstrates superior knowledge of some inner workings of the Mac, but in my script I did check to see if an reboot was required, and if not, would check again until no further updates were required. This worked well up through Yosemite.

There are also some osascript tricks for UI that I'm using you may find useful.

**Comment by thisaaronm** [comment]
@ChristopherA 

Good point on not all updates requiring a reboot. This was something I quickly threw together based off other scripts I've written in the past. I looked through your code and it does look more thorough (grepping for 'reboot', awking for macOS version, etc). And after looking at mine, I do see that it may reboot, even if there is no update to install (by my `softwareupdate --install --all && reboot`). I will need to fix that. At least, when doing `fdesetup authrestart`, it prompts the user for their credentials, so it doesn't kick the workstation immediately.  

I've used osascript in the past when I had a cron job running every minute, and wanted an "in your face" notification, but given that this script would be run from Terminal to begin with (at least, that's how I envisioned it), I don't find it necessary to incorporate GUI elements, though I can see how it can be valuable to some users. 

That being said, to the points you made in this issue:
- I'll see what I can do about checking if reboot is required...
- and if so, inform the user. Though as mentioned above, I try to not use GUI if I don't need to, so I'll probably add in a "Press any key to reboot, or CTRL+C to cancel..." prompt before rebooting, instead of just exiting the script and requiring the user to reboot through the GUI.

But I think I need to wait until I have updates available to install before I can fix/test all this.

**Comment by ChristopherA** [comment]
Fancy GUI is certainly optional ;-)

**Comment by ChristopherA** [comment]
When I was more active working on this, I kept a small extra partition on my Mac just for testing my script. I then used Carbon Copy Cloner and a disk image to return that to my original 10.*.0 state to test again.

**Comment by ChristopherA** [comment]
There have been a few updates to High Sierra now. A good time to test this script again.

**Comment by thisaaronm** [comment]
@ChristopherA for some personal reasons, I haven't had the ability to work on this for a bit, but I'm working on it now. Barring unforeseen events, I'll push an update maybe sometime next week.

**Comment by ChristopherA** [comment]
Any new ETA?

**Comment by thisaaronm** [comment]
@ChristopherA I apologize for the delay. I did push some commits, but they were to the dev branch, which I should have mentioned. It's closer, but not quite done yet, but I should have some time this weekend to dig into more.
