### ISSUE TITLE
Option to install command-line utilities w/o Xcode

### ISSUE THREAD

**Issue by ChristopherA** [thisaaronm/macOS_softwareUpdate#3]
It would be useful in the interactive version of this script that if the command-line utilities are not installed (as in a stock new 10.13.0 installation) that the script would offer to install the command-line utilities after all system updates are done.

Currently I have to use my old script (which used to work cleanly but doesn't work anymore but does install the first .0 command-line utilities) and then use your script to update it to .1.

**Comment by thisaaronm** [comment]
will consider this, though it's not really directly related or required for software updates. there are definitely things that would be handy to be installed that the user could be prompted to install, but i feel like that sort of falls slightly outside of the scope of what i originally intended this for. 

that being said, i'll think about including the option for using flags/options, so that if someone did want the cli utils, they could just add the flag for it, instead of including it interactively.
